spring:
  r2dbc:
    url: r2dbc:pool:mysql://localhost:3306/backend?autoReconnect=true&useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: root
    password: 1234

  data:
    r2dbc:
      repositories:
        enabled: true